### ISSUE TITLE
one to one mapping of job-queue and computing environment

### ISSUE THREAD

**Issue by Shiva7071007** [terraform-aws-modules/terraform-aws-batch#13]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

in this registry, each job queue is mapped to each computing environment.  what if I want one-to-one mapping of job queue and compute env like
high_priority_job_queue -> farget_compute_env
low_priority_job_queue -> farget_spot_compute_env

## Describe the solution you'd like.

example covering the above case, or a small change that I can do in module for personal use

## Describe alternatives you've considered.

NA

## Additional context

NA

**Comment by iamcgn** [comment]
I think you can solve this by just creating 2 separate modules in your own terraform. You'd have to duplicate job definitions if those are common for you but that's not the end of the world. I put this module in it's own module in my project and set up variables to create the 2 separate queues and compute environments for me. If that doesn't work for you, this is just a convenience module. You can always just create the same resources individually. It's a little more work but, honestly, not a ton.

**Comment by Shiva7071007** [comment]
> I think you can solve this by just creating 2 separate modules in your own terraform. You'd have to duplicate job definitions if those are common for you but that's not the end of the world. I put this module in it's own module in my project and set up variables to create the 2 separate queues and compute environments for me. If that doesn't work for you, this is just a convenience module. You can always just create the same resources individually. It's a little more work but, honestly, not a ton. 

Yup, I took reference from your module and created two modules for my use case.
