### ISSUE TITLE
attemptDurationSeconds

### ISSUE THREAD

**Issue by siarheikarabeika** [terraform-aws-modules/terraform-aws-batch#14]
https://github.com/terraform-aws-modules/terraform-aws-batch/blob/3484a97596785c590e21a4594c092a4aa538b096/main.tf#L287

Please have a loot at attempt_duration_seconds
AWS Batch use attemptDurationSeconds
https://docs.aws.amazon.com/batch/latest/userguide/job_timeouts.html

**Comment by bryantbiggs** [comment]
please fill in the issue template as provided - I am not sure what you are inquiring about here
