### ISSUE TITLE
having scheduling priority available with the module in job definitions

### ISSUE THREAD

**Issue by gce1estine** [terraform-aws-modules/terraform-aws-batch#26]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.

  - Yes ✅: please list the AWS provider version which introduced this functionality : 5.32.0

## Is your request related to a problem? Please describe.
Scheduling priority is not set while using the module but correctly set when using the ressource in job definitions 

## Describe the solution you'd like.
scheduling_priority parameter available in the module

## Describe alternatives you've considered.
as of now, will use the resource to create the job definitions 

## Additional context
N.A.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.0.0 :tada:
