### ISSUE TITLE
Pls drop latest version to registry

### ISSUE THREAD

**Issue by alexgoddity** [terraform-aws-modules/terraform-aws-batch#33]
16:40:57.618 STDOUT terraform: │ Error: Unresolvable module version constraint
16:40:57.618 STDOUT terraform: │ 
16:40:57.618 STDOUT terraform: │   on batch.tf line 11:
16:40:57.618 STDOUT terraform: │   11: module "user_images_batch_job_batch" {
16:40:57.618 STDOUT terraform: │ 
16:40:57.618 STDOUT terraform: │ There is no available version of module
16:40:57.618 STDOUT terraform: │ "registry.terraform.io/terraform-aws-modules/batch/aws" (batch.tf:11) which
16:40:57.618 STDOUT terraform: │ matches the given version constraint. The newest available version is
16:40:57.618 STDOUT terraform: │ 2.0.2.

PLS update latest to registry
![Screenshot 2024-08-29 at 16 47 23](https://github.com/user-attachments/assets/3dd93b52-6635-425d-ad8e-7b5511bb3bf2)

![Screenshot 2024-08-29 at 16 47 33](https://github.com/user-attachments/assets/9783f33d-4338-4441-831d-1ac6eb8ab2c3)

**Comment by bryantbiggs** [comment]
oy, this registry sync is a real PITA - cc @antonbabenko for the manual button update

**Comment by antonbabenko** [comment]
Fixed
