### ISSUE TITLE
Values for "VCPU" and "MEMORY" should be strings instead of numbers

### ISSUE THREAD

**Issue by ehtung** [terraform-aws-modules/terraform-aws-batch#4]
https://github.com/terraform-aws-modules/terraform-aws-batch/blob/b0b3857399c5030d4c34519f363be1abb789dd59/examples/fargate/main.tf#L132

Having numbers as values for `VCPU ` and `MEMORY` like in this example will cause:

    Error: AWS Batch Job container_properties is invalid: Error decoding JSON: json: cannot unmarshal number into Go struct field ResourceRequirement.ResourceRequirements.Value of type string

**Comment by bryantbiggs** [comment]
I'm not sure if there were any provider level changes since this was published but the example provided used to work. Regardless, its an easy fix to just wrap the numeric values in quotes - no changes are required to the module definition
